### ISSUE TITLE
Time dropdown will degrade after clicking to change

### ISSUE THREAD

**Issue by marcellusmontilla** [LicaGroup/Unliride#14]
![screen shot 2017-07-31 at 7 24 17 pm](https://user-images.githubusercontent.com/25737631/28775697-ef896286-7625-11e7-8ff8-5b3a5882632f.jpg)
![screen shot 2017-07-31 at 7 24 32 pm](https://user-images.githubusercontent.com/25737631/28775700-f48bf01e-7625-11e7-9507-1a27902f12a3.jpg)

**Comment by yzaldevs** [comment]
How you click change?

**Comment by marcellusmontilla** [comment]
Kapag pinindot mo yung 07 sa top picture, nagiging ganun sa bottom picture.

**Comment by marcellusmontilla** [comment]
![screen shot 2017-08-02 at 11 28 55 am](https://user-images.githubusercontent.com/25737631/28856465-d6dc56d4-7775-11e7-9873-303962e3c625.jpg)

**Comment by marcellusmontilla** [comment]
Ganito yung ideal katulad ng nasa LMS:
![screen shot 2017-08-02 at 11 31 33 am](https://user-images.githubusercontent.com/25737631/28856530-41fa1686-7776-11e7-9a2e-101d32c766a8.jpg)

**Comment by yzaldevs** [comment]
Ok na. Nagulo lang yung design

**Comment by marcellusmontilla** [comment]
closed by a5a807bb3fee382abd26e437966f8fd1ef06e5c9
