### ISSUE TITLE
Wrong spelling "verifcation" in sign-up text

### ISSUE THREAD

**Issue by marcellusmontilla** [LicaGroup/Unliride#15]

**Comment by yzaldevs** [comment]
Add screen shot so I can fixed it fast.

**Comment by yzaldevs** [comment]
I can't find it

**Comment by yzaldevs** [comment]
Add screenshot

**Comment by marcellusmontilla** [comment]
![img_0800](https://user-images.githubusercontent.com/25737631/28856382-43a4cfe0-7775-11e7-9023-5b7a4c2564b8.PNG)

**Comment by marcellusmontilla** [comment]
fixed by a5a807bb3fee382abd26e437966f8fd1ef06e5c9
