### ISSUE TITLE
Dropdown of area code at login

### ISSUE THREAD

**Issue by marcellusmontilla** [LicaGroup/Unliride#20]

**Comment by yzaldevs** [comment]
Bakit?

**Comment by marcellusmontilla** [comment]
may foreign clients na pwede mgbook outside the country for airport transfer to their hotel

**Comment by yzaldevs** [comment]
bigyan niyo ako ng list ng country code with pictures

**Comment by marcellusmontilla** [comment]
mgagamit mo ba [ito](http://www.jqueryscript.net/form/jQuery-International-Telephone-Input-With-Flags-Dial-Codes.html)?

**Comment by yzaldevs** [comment]
country code + 10 digits ba lagi yung number?

**Comment by marcellusmontilla** [comment]
yes, standard yung 10 digits sa mobile phones
