### ISSUE TITLE
Add robots.txt to disallow indexing until first official release of unliride.com

### ISSUE THREAD

**Issue by marcellusmontilla** [LicaGroup/Unliride#21]

**Comment by yzaldevs** [comment]
Ano yan?

**Comment by marcellusmontilla** [comment]
Wag natin ipa-index yung site kasi hindi pa nman working, dpat hindi sya lalabas sa search.
Parang kapag ngpakasal yung babae, hindi mo ipapakita yung gown kung hindi pa gagamitin.

**Comment by yzaldevs** [comment]
Pano niyo mattest?

**Comment by marcellusmontilla** [comment]
direct URL type lang, ayaw lang natin na lumabas sa search ang unliride.

**Comment by yzaldevs** [comment]
Na try niyo bang i-search? Github lang yung lumababas. Walang details or description yung page kaya di nila massearch basta basta

**Comment by marcellusmontilla** [comment]
preventive measure lang yan na hindi nman mahirap gawin

**Comment by yzaldevs** [comment]
pano ba gawin yan?

**Comment by marcellusmontilla** [comment]
[Ito](http://www.robotstxt.org/robotstxt.html) ang gawin mong reference
